# Generated by Django 2.0.6 on 2018-07-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(null = True)),
                ('UserID', models.CharField(max_length=250 , blank = True)),
                ('Word', models.CharField(max_length=250 , blank = True)),
                ('Pronunciation', models.CharField(max_length=250 , blank = True)),
                ('Phrase', models.CharField(max_length=250 , blank = True)),
                ('Hint', models.CharField(max_length=250 , blank = True)),
                ('Definition', models.CharField(max_length=500 , blank = True)),
                ('Synonym', models.CharField(max_length=250 , blank = True)),
                ('Is_ShareOnline', models.CharField(max_length=250 , blank = True)),
                ('Is_Favourite', models.CharField(max_length=250 , blank = True)),
                ('IsSkip', models.CharField(max_length=250 , blank = True)),
                ('Appearance', models.CharField(max_length=250 , blank = True)),
                ('WAppreance', models.CharField(max_length=250 , blank = True)),
                ('Score', models.IntegerField(null = True)),
                ('Addition_Info', models.CharField(max_length=250 , blank = True)),
            ],
        ),
    ]
