# Generated by Django 2.0.6 on 2018-07-09 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addwords',
            name='Addition_Info',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='addwords',
            name='Appearance',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='addwords',
            name='Definition',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='addwords',
            name='Hint',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='addwords',
            name='IsSkip',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='addwords',
            name='Is_Favourite',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='addwords',
            name='Is_ShareOnline',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='addwords',
            name='Phrase',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='addwords',
            name='Pronunciation',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='addwords',
            name='Score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addwords',
            name='Synonym',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='addwords',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addwords',
            name='WAppreance',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='addwords',
            name='Word',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='addwords',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
